name: zo_animated_border
description: "Add animated, glowing, and gradient borders to any Flutter widget
  with zo_animated_border – a powerful and flexible package for modern UIs."
version: 1.0.9
repository: https://github.com/Oauth-Celestial/zo_animated_border

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
screenshots:
  - description: zo_animated_border
    path: assets/border.png

